# Exercise 02

Estimate a classifier to predict churn

## Problem Formulation

Customer Churn: losing/attrition of the customers from the company. Especially, the industries that the user acquisition is costly, it is crucially important for one company to reduce and ideally make the customer churn to 0 to sustain their recurring revenue. If you consider customer retention is always cheaper than customer acquisition and generally depends on the data of the user(usage of the service or product), it poses a great/exciting/hard problem for machine learning.

## Data

Dataset is from a telecom service provider where they have the service usage(international plan, voicemail plan, usage in daytime, usage in evenings and nights and so on) and basic demographic information(state and area code) of the user. For labels, I have a single data point whether the customer is churned out or not.

In [106]:
# Download the dataset
from urllib import request
response = request.urlopen('https://raw.githubusercontent.com/EricChiang/churn/master/data/churn.csv')
raw_data = response.read().decode('utf-8')

In [108]:
# Convert to numpy
import numpy as np
data = []
for line in raw_data.splitlines()[1:]:
    words = line.split(',')
    data.append(words)
data = np.array(data)
column_names = raw_data.splitlines()[0].split(',')
n_obs = data.shape[0]

In [109]:
print(column_names)
print(data.shape)

['State', 'Account Length', 'Area Code', 'Phone', "Int'l Plan", 'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls', 'Day Charge', 'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins', 'Night Calls', 'Night Charge', 'Intl Mins', 'Intl Calls', 'Intl Charge', 'CustServ Calls', 'Churn?']
(3333, 21)


In [110]:
data[:2]

array([['KS', '128', '415', '382-4657', 'no', 'yes', '25', '265.100000',
        '110', '45.070000', '197.400000', '99', '16.780000', '244.700000',
        '91', '11.010000', '10.000000', '3', '2.700000', '1', 'False.'],
       ['OH', '107', '415', '371-7191', 'no', 'yes', '26', '161.600000',
        '123', '27.470000', '195.500000', '103', '16.620000', '254.400000',
        '103', '11.450000', '13.700000', '3', '3.700000', '1', 'False.']], 
      dtype='<U10')

In [111]:
# Select only the numeric features
X = data[:, [1,2,6,7,8,9,10]].astype(np.float)
# Convert bools to floats
X_ = (data[:, [4,5]] == 'no').astype(np.float)
X = np.hstack((X, X_))
Y = (data[:, -1] == 'True.').astype(np.int)

In [112]:
X[:2]

array([[ 128.  ,  415.  ,   25.  ,  265.1 ,  110.  ,   45.07,  197.4 ,
           1.  ,    0.  ],
       [ 107.  ,  415.  ,   26.  ,  161.6 ,  123.  ,   27.47,  195.5 ,
           1.  ,    0.  ]])

In [113]:
print('Number of churn cases ', Y.sum())

Number of churn cases  483


# Exercise 02.1

Split the training set in two sets with 70% and 30% of the data, respectively.

---
Partir la base de datos es dos partes de 70%

In [114]:
# Insert code here
random_sample = np.random.rand(n_obs)
X_train, X_test = X[random_sample<0.6], X[random_sample>=0.6]
Y_train, Y_test = Y[random_sample<0.6], Y[random_sample>=0.6]

print(X_train.shape, X_test.shape)
print(Y_train.shape, Y_test.shape)

(2013, 9) (1320, 9)
(2013,) (1320,)


In [115]:
Primera_X=X[0:2334]
Primera_Y=Y[0:2334]

In [116]:
print(Primera_X.shape)
print(Primera_Y.shape)

(2334, 9)
(2334,)


In [117]:
Segunda_X=X[2334:3333]
Segunda_Y=Y[2334:3333]

In [118]:
print(Segunda_X.shape)
print(Segunda_Y.shape)

(999, 9)
(999,)


# Exercise 02.2

Train a logistic regression using the 70% set

---
Entrenar una regresion logistica usando la particion del 70%

In [119]:
# Insert code here
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

# Exercise 02.3

a) Create a confusion matrix using the prediction on the 30% set.

b) Estimate the accuracy of the model in the 30% set

---
a) Estimar la matriz de confusion en la base del  30%.

b) Calcular el poder de prediccion usando la 

In [120]:
# Insert code here
y_pred = clf.predict(X_test)

from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, y_pred)

array([[1105,   26],
       [ 165,   24]])

In [121]:
(Y_test == y_pred).mean()

0.85530303030303034

In [122]:
%matplotlib inline
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
sns.set();
cmap = mpl.colors.ListedColormap(sns.color_palette("hls", 3))

In [123]:
X, y = Segunda_X, Segunda_Y
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
pca.fit(X)
X_reduced = pca.transform(X)
X_reduced.shape

(999, 3)

In [124]:
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=2, random_state=0) # Fixing the RNG in kmeans
k_means.fit(X)
y_pred = k_means.predict(X)

In [125]:
from sklearn.metrics import confusion_matrix

# Compute confusion matrix
cm = confusion_matrix(y, y_pred)
np.set_printoptions(precision=2)
print(cm)

[[395 435]
 [106  63]]


In [126]:
(y == y_pred).mean()

0.45845845845845845